# fly.toml app configuration file generated for late-plate-bot-green-shape-1404 on 2025-07-17T21:37:28-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'late-plate-bot-green-shape-1404'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
BASE_URL="https://api.groupme.com/v3"